on:
  workflow_dispatch:
    inputs:
      account:
        description: 'NR Account'
        required: true
        type: number
      nrak_key:
        description: 'Sua NRAK- API KEY'
        required: true
        type: string
      yourlib:
        description: 'Biblioteca .jar'
        required: true
        type: string
      outputfile:
        description: 'Nome do report'
        required: true
        type: string

  push:
    branches:
      - main
name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
jobs:
  newrelic-env-exporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install axios
      - run: ./search.js -a ${{ inputs.account }} -k ${{ inputs.nrak_key }} --field-modules --starts ${{ inputs.yourlib }} --out ${{ inputs.outputfile }}