on:
  workflow_dispatch:
  push:
    branches:
      - main
name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
jobs:
  newrelic-env-exporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install axios
      - run: ./search.js -h